services:
  # Spring Boot Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laura-nagamine-backend
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      SONAR_PROJECT_KEY: ${SONAR_PROJECT_KEY:-laura-nagamine-backend}
      SONAR_PROJECT_NAME: ${SONAR_PROJECT_NAME:-Laura Nagamine Backend}
      SONAR_HOST_URL: ${SONAR_HOST_URL:-http://213.199.42.57:9002}
    ports:
      - "${SERVER_PORT:-8080}:8080"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
